version: '3.8'

services:
  app:
    image: 'online_store:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      APPLICATION_PROPERTIES: $APPLICATION_PROPERTIES
    stdin_open: true
    tty: true
    volumes:
      - ./src/main/resources/static/images/products:/app/data/static/images/products
      - ./src/main/resources/static/images/reviews:/app/data/static/images/reviews

  postgres:
    image: postgres:15.4-alpine
    container_name: 'postgres_container'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345^qwertY
      POSTGRES_DB: store_db
    restart: always

